### ISSUE TITLE
unable to backup priviledged files

### ISSUE THREAD

**Issue by fw8** [vshn/k8up#107]
The **restic** command seems to run with uid 1001 and is therfor not able to backup files owned by other users (e.G. **root**).
Is there a possibility to run the **restic** command as **root** (by setting the **securityContext** of the job pod or so..)?

**Comment by Kidswiss** [comment]
Hi @fw8 

The current helm chart uses an older image for the restic jobs. Can you adjust the helm values so it uses `v0.1.9`? https://github.com/appuio/charts/blob/master/k8up/values.yaml#L26

That should solve your issues. 

Best
Simon

**Comment by fw8** [comment]
Ahhh... I understand! "USER 1001" was removed from the more recent wrestic image. I was confused because didn't saw this in the master branch of the repo.

Thanks for the hint. Everything works fine now.

**Comment by Kidswiss** [comment]
Perfect!

I opened a PR on the charts repository to use v0.1.9 by default.
