### ISSUE TITLE
Improved K8up operator monitoring

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#11]
Add a lot more of monitoring information to the operator to close the gap.

Operator:
* global view over all registered backups (how many schedules for example)
* reports failed successful runs (as in backoff limit was reached/crashed/etc.)
* could also report how many jobs are queued up due to a blocking prune run
* with that info it could be possible to find out if a backup job is late

Wrestic:
* more granular per job info
* how many file errors, changes, etc (as already implemented)
* start/end time

refs APPU-1058

**Comment by Kidswiss** [comment]
Was merged with https://github.com/vshn/k8up/pull/60.

Closing the issue.
