### ISSUE TITLE
Limit max concurrent jobs

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#120]
The operator should have the ability to limit how many jobs should get run concurrently.

This limit should be configurable by job type (prune, backup, check, etc.)

**Comment by Schnitzel** [comment]
additonal thing: run only one backup/prune/check per repo/s3-bucket.
As I don't think you can backup to the same repo/s3-bucket at the same time?

**Comment by Kidswiss** [comment]
@Schnitzel concurrent backups to the same repository are supported by restic.

**Comment by susana-garcia** [comment]
I'll take this one
