### ISSUE TITLE
Add Restore jobs to the rewrite

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#126]
Add the check job logic to the new implementation: https://github.com/vshn/k8up/tree/master/service/restore

The controller is already implemented for that. Now we need to implement an Executor that actually triggers the job.

With #114 merged the new implementation lives on the development branch.

**Comment by mweibel** [comment]
I'll take that over 👍

**Comment by mweibel** [comment]
wondering - is a restore exclusive? 
It sounds like it should but I can't seem to find it in the existing code.
