### ISSUE TITLE
Add prometheus metrics to the rewrite

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#127]
The rewrite currently doesn't contain any k8up metrics.

The operator-sdk provides a default metrics endpoint though. So use that one to add the custom metrics, if possible.

Most metrics are defined in the observer or the scheduling in the old version:
https://github.com/vshn/k8up/blob/master/service/schedule/scheduleRunner.go#L30
https://github.com/vshn/k8up/blob/master/service/observe/subscription.go#L23

With #114 merged the new implementation lives on the development branch.

**Comment by susana-garcia** [comment]
I'll take this

**Comment by susana-garcia** [comment]
@Kidswiss quick question related to this task: what’s the best way to setup prometheus in my local cluster for dev mode?

**Comment by Kidswiss** [comment]
@susana-garcia I usually just `curl'd` the `/metrics` endpoint to see if the metrics show up. As they are plain text it's pretty easy to verify that way.

**Comment by susana-garcia** [comment]
@Kidswiss ok, thanks!
