### ISSUE TITLE
Add automated integration and unit tests

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#129]
## Summary

**As** K8up developer\
**I want** automated whitebox tests of K8up internals \
**So that** I can contribute tested features and changes to ensure quality *and* avoid accidental breaking changes

## Context

Currently it's unclear if there's a distinction between integration tests and unit tests.
A potential distinction could be:
* Integration tests: all tests that require a K8s Api server (envtest)
* Unit tests: function tests that can run without API server, to test microfunctions in code.

But in all honesty, it doesn't really make a difference. However, some IDEs may have difficulties to debug tests when envtest is running if those only run in `Makefile`.

## Out of Scope

* Implement e2e tests
* Implement tests that are part of (w)restic itself
* Achieve a certain code coverage threshold. code coverage as metric doesn't say much about actual quality.

## Further links

* [Tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/testing/)
* [Inspiration in Espejo](https://github.com/vshn/espejo)

## Acceptance criteria

*Given* a K8up PR\
*When* I push code into a feature branch\
*Then* GitHub should run automated tests and indicate to code authors and reviewers of passing or failing tests

## Implementation Ideas

* The Operator-SDK scaffolds tests with envtest, a library that runs a minimal Kubernetes API server in memory where we get full support for Kubernetes client operations

**Comment by ccremer** [comment]
#152 sets the foundation for this case, at least locally (not in GH action yet)

**Comment by ccremer** [comment]
@Kidswiss I have refined this issue. Please review

**Comment by tobru** [comment]
As discussed in today's Tarazed sync we'll close this issue in favor of the outcome of the discussion in https://github.com/vshn/k8up/discussions/231. We'll create appropriate individual issues to increase test coverage.
