### ISSUE TITLE
Extend K8up Status resources with Conditions

### ISSUE THREAD

**Issue by mweibel** [vshn/k8up#138]
## Summary

**As** K8up User\
**I want** more information in the status fields of objects\
**So that** I know in what state my backups and restores are and where to investigate failures.

## Context

Error handling is currently done via logs. But we cannot assume that every K8up user has access to view the K8up operator Logs. Thus we should incorporate error handling directly via Status field of the affected resource.

## Out of Scope

* Replace existing status fields, which could result in a breaking change of the CRDs. Updating the CRD definition with just field additions should be backwards compatible.

## Further links

* [Conditions](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions)
* [Blog post](https://dev.to/maelvls/what-the-heck-are-kubernetes-conditions-for-4je7#orthogonality-vs-extensibility)

## Acceptance criteria

*Given* an existing K8up CRD object\
*When* K8up reconciles an object\
*Then* the object's `.status` field should be updated

*Given* an existing K8up CRD object\
*When* K8up encounters an error during reconcile\
*Then* the object's `.status` field should be updated with a clear error message

*Given* an existing K8up CRD object with error in the status field\
*When* K8up reconciles successfully after a failed attempt\
*Then* the object's `.status` field should be cleared from any errors.
## Implementation Ideas

* Use Kubernetes Conditions to reflect an orthogonal "state" machine.

**Comment by ccremer** [comment]
I would also welcome this. Just adding conditions without removing/changing the existing ones is backwards compatible (e.g. we can just run the operator and after reconcile the existing objects will get the new conditions). 
However, if we remove existing status fields from the CRD, would we need to make a new API version? (v1alpha2)
Maybe the K8s deserializer can ignore status fields that aren't expected in the CRD definition

**Comment by ccremer** [comment]
I took the liberty to refine this feature request

**Comment by Kidswiss** [comment]
> Maybe the K8s deserializer can ignore status fields that aren't expected in the CRD definition

We can test this while implementing this I guess, by simply removing the old status fields, running the operator and see what happens.

**Comment by ccremer** [comment]
I think it's the other way round: Remove the status fields from the CRD, update CRD, add status fields in the YAML of an object, then run Operator. I expect either:
1. The unknown status fields are left as-is, which would be kinda "bad", as they won't get cleaned
2. The operator removes unknown status fields and only stores the one it knows

**Comment by Kidswiss** [comment]
Well the first one isn't that bad. As the operator will clean up older jobs anyways. So the amount of CRs with the old status fields should die out rather quickly. For some clusters it's configured to keep no older Jobs at all.
