### ISSUE TITLE
HA for Operator

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#14]
Implement high-availability for the operator so that more than once operator can run per cluster.

refs APPU-1623 and APPU-1625

**Comment by ccremer** [comment]
With the move to Operator SDK 1.0+ we have now leader election enabled by default. That means there can be multiple replicas but only one will be the master. If the master goes down, the others will elect a new leader. Is that sufficient for this case? However, there's no K8up release (except master) yet.

If yes, please close

**Comment by tobru** [comment]
This is good enough for now.
