### ISSUE TITLE
typo in env var BACKUP_GLOBALRESTORES3ACCESKEYID

### ISSUE THREAD

**Issue by mweibel** [vshn/k8up#141]
There's an `s` missing in the `Acces*s*` part. Unsure what implications this has, but might be unpleasant 😄

**Comment by Kidswiss** [comment]
🤦‍♂️

Well fixing that one would probably break a few operator configurations. But if we mark it in the changelog as a breaking change it should be fine.

**Comment by tobru** [comment]
Won't do, will be fixed in #121

**Comment by Kidswiss** [comment]
While testing I found that this typo doesn't seem to be in the legacy K8up releases. So we should fix it or we'll actually break backwards compatibility :D

**Comment by ccremer** [comment]
Can confirm it: https://github.com/vshn/k8up/blob/v0.1.10/config/global.go#L43
However, the documentation states otherwise: https://github.com/vshn/k8up/blob/v0.1.10/docs/modules/ROOT/pages/advanced-config.adoc

**Comment by ccremer** [comment]
This is fixed now in master, it was a documentation issue.
The config refactoring itself is in a separate PR
