### ISSUE TITLE
CRD compatibility support discussion

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#153]
### Issue

The current CRD generated is of version `apiextensions.k8s.io/v1beta1`, but some generated properties aren't valid for that version in K8s 1.18+. The generator currently used could do `apiextensions.k8s.io/v1` if we upgrade it, but `v1` is not available in older Kubernetes server versions (e.g. OpenShift 3.11), that means we would not be able to install K8up.

### Proposal

In order to stay compatible with both Openshift 3.11 and also Kubernetes 1.18+ (Rancher, K3s etc) I propose:

1. Generating the CRD with controller-gen 0.4+ but for spec v1beta1, make the necessary post-generate-patches to make it work. The YAML files are saved in `config/crd/apiextensions.k8s.io/v1beta1/` (see #152 )
2. Additionally generate the CRD with controller-gen 0.4+, save the YAML files in `config/crd/apiextensions.k8s.io/v1/`
3. Make both CRD versions available in GitHub releases for download (attachment)
4. For development we use `v1` to stay up-to-date with Operator SDK (which will eventually also migrate to controller-gen 0.4+) and K8s API.
    * Also because we are developing the Operator against K8s 1.18 API and beyond
    * Use GitHub actions to run e2e tests (with KIND) for a pre-1.18 cluster and post-1.18 cluster version (matrix jobs)

### Background

* In #114 we have migrated K8up to Operator SDK 1.0+. Operator SDK uses controller-gen version 0.3.0
* controller-gen 0.4.x uses `v1` by default
* Reason why it can't be installed:
```
The CustomResourceDefinition "prebackuppods.backup.appuio.ch" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[pod].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[pod].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
make: *** [Makefile:163: setup_e2e_test] Error 1
```

* v1beta1 is deprecated and will be removed in 1.22:
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```
* I think 1.22 is coming sooner than we can get rid of Openshift 3.11

**Comment by Kidswiss** [comment]
Is the bug fixed in controller-gen 0.4 that creates the broken protocol fields?

I like your proposal, but the versions in the paths are a bit confusing as it's not clear that the version of `apiextensions.k8s.io` is meant and not of `backup.appuio.ch`. Maybe instead use the target k8s version? e.g. `config/crd/k8s18` for k8s 1.18+ and `config/crd/k8s17` for 1.17 and below?

**Comment by ccremer** [comment]
Yes, in https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.1 it's fixed specifically for corev1.Protocol
I fear it will then use `v1`, but I'll test it out locally

**Comment by Kidswiss** [comment]
Isn't there some flag or something to ensure backward compatibility?

**Comment by ccremer** [comment]
Ok, so:
* `controller-gen@0.4.1 crd:trivialVersions=true crd:crdVersions=v1beta1 ...` generates the old CRDs, but with the protocol, so the post-generator-patch is still necessary
* `controller-gen@0.4.1 crd:trivialVersions=true crd:crdVersions=v1 ...` generates the CRD without the `protocol` property, but it's v1 and thus incompatible

Regarding directory structure:
Your proposal could also be misleading. The CRD v1beta1 with the patch are still valid for 1.18 until 1.21. The v1 was introduced v1.16, so we have an overlap of the same versions.

What about `config/crd/apiextensions.k8s.io/v1[beta1]/...` ?

**Comment by Kidswiss** [comment]
Sounds good to me.
