### ISSUE TITLE
End-to-End testing framework research

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#156]
With #154 we have set the groundwork for e2e testing with KIND. What's left are the actual e2e tests themselves.
In https://github.com/vshn/espejo we set up e2e tests with bash, but it's considered experimental. We have chosen to go with bash for the following reasons:
* Actual user perspective. There's an actual cluster and we don't add resources programmatically. Each step could be done by a user also (`kubectl apply -f ..` etc)
* Currently, there are just 2-3 smoke tests, the rest is tested in unit and integration tests.

In https://github.com/vshn/wrestic/blob/master/TESTCASES.md, there are a bunch of Testcases, ideal candidates for automation.

There is also the question of concern: Should K8up include e2e testcases where the whole stack is tested? Or should part of the tests be automated in wrestic, while the e2e tests for K8up really test the Operator features and not transparently wrestic also.

**Comment by ccremer** [comment]
Did a little research for https://github.com/bats-core/bats-detik

* can run bash commands
* has assertions (comes with a certain syntax)
* Has even a e2e test linter

Downsides:
* npm/node is needed to install/run

I suggest to still give it a go

**Comment by tobru** [comment]
This tool looks promising, we should give it a go :+1:

**Comment by Kidswiss** [comment]
> Or should part of the tests be automated in wrestic,

Well parts of the tests are already automated in the wrestic integration tests. So I'd say there's no need to test things twice.

We should think carefully what we want to test. The operator is mostly only responsible to create the right batch jobs at the right time. The actual functionality is done in Wrestic. so my proposal:

* Integration tests with the operator shouldn't necessarily test if the backups are done, but rather if the jobs are created as they are supposed to with the given params.
* integration tests in wrestic should test the actual backups and restores (already implemented).
