### ISSUE TITLE
Migrate K8up to Project Syn

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#167]
## Summary

Migrate K8up to Project Syn GitHub Organization (https://github.com/projectsyn/), adapt the code, docs and description accordingly and therefore make it a integral part of Project Syn.

## Context

K8up needs a home with a good community infrastructure. Project Syn has that and is building up what's needed to be as open to contributors as possible.

## Out of Scope

* Rename K8up, the name must stay

## Further links

* New GitHub org: https://github.com/projectsyn/

## Acceptance criteria

* Code adapted (go.mod, imports etc)
* Documentation updated
* Deprecate docker images (these repos won't receive any new pushes): 
  * docker.io/vshn/k8up
  * docker.io/vshn/wrestic
  * quay.io/vshn/k8up
  * quay.io/vshn/wrestic
* Copied all image tags from `[docker.io,quay.io]/vshn/[k8up,wrestic]` to `[docker.io,quay.io]/projectsyn/[k8up,wrestic]`
* Created follow-up task to delete `[docker.io,quay.io]/vshn/[k8up,wrestic]` later (Date tbd)

**Comment by ccremer** [comment]
What shall we do with the images in Docker Hub and Quay.io? shall we 
* keep vshn/k8up, but don't maintain it anymore, to keep deployments working
* keep vshn/k8up for a deprecation period. Users are required to migrate, but can plan it in a reasonable timeframe.
* move all tags to projectsyn/ with breaking deployments, but that would make it explicit to maintainers. But also generate emergency-like work

**Comment by tobru** [comment]
I'd go for the deprecation period and get rid of `vshn/k8up` in due time.

**Comment by ccremer** [comment]
Updated description accordingly

**Comment by marcellanz** [comment]
With the migration, the K8up logo with its 8 spokes, could be aligned in the honor of [Seven of Nines legacy](https://en.wikipedia.org/wiki/Kubernetes#History) with the k8s project.

**Comment by tobru** [comment]
> With the migration, the K8up logo with its 8 spokes, could be aligned in the honor of Seven of Nines legacy with the k8s project.

See https://github.com/vshn/k8up/pull/350 :smile:

**Comment by tobru** [comment]
After some discussions we decided to not move K8up into Project Syn as the scope of these two projects is very different. Instead we'll go for its own GitHub org in #458.
