### ISSUE TITLE
Define K8up Versioning and Release Process

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#208]
## Summary

**As** K8up developer
**I want** to know how the release process works and how the versioning scheme looks like
**So that** release are a breeze and versioning is consistent and makes sense

## Context

The current release process is undefined (not documented / automated) and the versioning of K8up is arbitrary. The release process also doesn't take documentation into consideration.

## Out of Scope

* Automate the release process -> Should be handled in a separate issue once it's clear how the release process should look like

## Further links

* https://semver.org/
* https://docs.antora.org/antora/2.3/content-source-versioning-methods/
* [Automatically assign version to component based on reference (branch or tag) name (refname) if version not specified](https://gitlab.com/antora/antora/-/issues/296)

## Acceptance criteria

*Given* a new K8up release is imminent
*When* I want to do a new release
*Then* I know exactly what the new version will be and how the process works

## Implementation Ideas

* Use Semantic Versioning 2.0.0 as versioning scheme
* Document manual release process in README so that it later can be automated
* Create a branch and a tag per release (?)
* Release process must include: Release notes / Changelog, docs (version) update, ...

**Comment by ccremer** [comment]
It looks like the process has to be first defined and the result is purely documentation. Does it make sense to move this issue into a GH Discussion (so we can try out the beta)?

**Comment by tobru** [comment]
I have put some much :heart: into this issue :see_no_evil: Honestly: Yes, why not, I don't mind...
