### ISSUE TITLE
Automatically Generate CRD Docs in Asciidoc for Antora

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#210]
## Summary

**As** developer
**I want** to have automatically generated CRD documentation
**So that** documentation about CRDs is always automatically up-to-date

## Context

Currently the CRDs are manually documented in `docs/`. In Project Syn Lieutenant Operator we found a way to [automatically generate](https://github.com/projectsyn/lieutenant-operator/blob/master/create-api-docs.sh) this documentation. This should be ported to K8up.

## Further links

* https://github.com/projectsyn/lieutenant-operator/blob/master/create-api-docs.sh
* https://docs.syn.tools/lieutenant-operator/references/crds-html.html

## Acceptance criteria

CRD documentation is automatically generated in Asciidoc format.

## Implementation Ideas

Get inspiration for the work done in https://github.com/projectsyn/lieutenant-operator and port it over here.

**Comment by ccremer** [comment]
Can you use the given_when_then syntax in the acceptance criteria? I'm missing where/when the documentation is to be generated. Locally? In GH actions only & verified as a PR check if there are changes (git diff)? both?

**Comment by tobru** [comment]
I actually don't know that, that's part of this issue to figure it out.

**Comment by tobru** [comment]
We might just want to link to https://doc.crds.dev/github.com/vshn/k8up which is already great. What do others think?

**Comment by Kidswiss** [comment]
Fine by me.

Although we could use the same script as the lieutenant-operator uses, it creates something that's rendered correctly in asciidoc.

**Comment by ccremer** [comment]
I think this site is dynamically generated.
When I visited just now, the page load took several seconds...

If we can generate the docs with make and integrate into Antora, I think we should favor an approach where we have 1 documentation site and aren't dependent on external sites.

**Comment by tobru** [comment]
Thanks for the inputs - Let's keep the CRD docs in Antora as originally specified. We can still link to doc.crds.dev.
