### ISSUE TITLE
Backup reconciler fails if previous deployment for prebackuppods already exists

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#246]
## Describe the bug

Backup reconciler fails if previous deployment for prebackuppods already exists

## Additional context

* the backups are completely stopped.

## Logs

If applicable, add logs to help explain your problem.
```console
2020-12-23T15:09:07.156+0100	INFO	controllers.Backup	starting pre backup pod	{"backup": "drupal-example-test1-master/backupjob-1608420480", "namespace": "drupal-example-test1-master", "name": "mariadb-prebackuppod"}
2020-12-23T15:09:07.164+0100	ERROR	controllers.Backup	error while handling pre backup pods	{"backup": "drupal-example-test1-master/backupjob-1608420480", "error": "error creating pre backup pods: deployments.apps \"mariadb-prebackuppod\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/vshn/k8up/executor.(*BackupExecutor).startBackup
	/home/runner/work/k8up/k8up/executor/backup.go:156
```

## Expected behavior

K8up should either
* Create new deployments with different name
* Update existing deployment
* Recreate deployment

## To Reproduce

1. Create PrebackupPod spec
2. Schedule backups

## Environment (please complete the following information):

- Image Version: v1.0.0-rc1
- K8s Version: v1.18
- K8s Distribution: Rancher

**Comment by ccremer** [comment]
@Kidswiss what do you think would be the best action here?
I tend to go with `Create new deployments with different name`. Setting a unique name for each backup, and setting the controller reference to the backup CR ensures that we can always launch prebackup pods, and they're removed once the backup object has been removed (manually or with cleanup)

**Comment by Kidswiss** [comment]
@ccremer The problem with this approach is that wrestic will trigger the scripts for each instance it finds. So multiple deployments will result in triggering the same backup command from different instances of the same pod.

**Comment by ccremer** [comment]
So we go with the recreate approach?

**Comment by Kidswiss** [comment]
I'd say only recreate it, if the pod definitions actually changed, because we would could disrupt an already running script otherwise.

**Comment by ccremer** [comment]
so the reconcile should just continue on errors? or at least when its IsAlreadyExists error?

**Comment by Kidswiss** [comment]
I'd say that's currently the best approach, even though the cleanup of the wrestic pod that finishes first will probably abort any commands that are still running for the later wrestic pod.

I'd say running multiple backups in the same namespace with pre-backuppods is with the current implementation not really supported, due to the issues discussed here.
