### ISSUE TITLE
Reduce code repetition

### ISSUE THREAD

**Issue by cimnine** [vshn/k8up#264]
## Summary

**As** developer\
**I want** short and concise code that isn't repetitive unless it's necessary\
**So that** I can focus on implementing features and fixing bug rather than the internal consistency of the codebase.

## Context

[The `handler/schedule.go` code](https://github.com/vshn/k8up/blob/v1.0.0-rc2/handler/schedule.go#L82) is rather lengthy and repetitive. It should be checked if and how this code could be optimized, e.g. by extracting the repetitive parts into a function.

The problem is that the action types (i.e. check, backup, archive, ...) currently do not share a common type or interface. This makes it a non-trivial effort. It's also the reason why this is it's own issue.

## Out of Scope

* Changes to behaviour of k8up.

## Further links

* [Comment in PR 260](https://github.com/vshn/k8up/pull/260#pullrequestreview-562761032)

## Acceptance criteria

- Given the changes to the code, when the code climate report runs, it should have fewer complaints.
- Given the changes to the code, when the tests run, they must not fail.
- Given the changes to the code, when reading the code, it should still be simple to understand it's purpose.
- Given the changes to the code, when observing k8up from the outside, it should not have changed it's behaviour.

## Implementation Ideas

-

**Comment by Kidswiss** [comment]
@cimnine Is the title really supposed to be `Reduce`? :)

**Comment by ccremer** [comment]
this goes into the same direction as #247 , the other one is more generic though. Shall we consolidate or close one of the two?
