### ISSUE TITLE
Change Default S3 Storage Policy to Enable Encryption at Rest and a Default Block to Public Access

### ISSUE THREAD

**Issue by cdchris12** [vshn/k8up#300]
## Summary

**As** a user of k8up\
**I want** restic backup data stored in S3 repos to be stored encrypted at rest by default and made unavailable for public access\
**So that** this data is less easily obtained by unauthorized users

## Context

We would like to store data encrypted at rest wherever possible. Since k8up creates all properties of an S3 bucket if it does not already exist, we would propose that the operator automatically configure this encryption at rest during the bucket's initial setup. In a similar vein, we would also like all public access to be blocked to these items.

## Out of Scope

* We do not expect the operator to reconfigure any buckets or objects which already exist; this applies to newly created buckets only

## Further links

* https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketEncryption.html
* https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutPublicAccessBlock.html

## Acceptance criteria

*Given* a backup schedule with an S3 bucket which must be newly created by the operator\
*When* the s3 bucket is created\
*Then* encryption at rest and blocking of public access to the bucket and all its objects is enabled

## Implementation Ideas

* Encryption can be enabled on a bucket via a call to the `PutBucketEncryption` API
* Public access block can be enabled via a call to the `PutPublicAccessBlock` API

**Comment by tobru** [comment]
Thanks for this idea. Creation of S3 buckets is done by [Restic itself](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3), K8up doesn't play a role here.

We discussed the possibility to add features for bucket management in to K8up but came to the conclusion that this shouldn't be part of K8up but rather an external tool which is meant for doing that. A pre-provisioned bucket can be easily consumed by K8up.

In the past we experimented a lot with [Crossplane](https://crossplane.io/) which is able to manage S3 buckets, including configuring the bucket in every aspect. See [provider-aws Bucket](https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.16.0) and [provider-aws BucketPolicy](https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/BucketPolicy/v1alpha2@v0.16.0) for possible options. The resulting connection secret is easily consumable by K8up. That means K8up and Crossplane work very well together.

Another option would be to open an issue at https://github.com/restic/restic/issues and ask for these options.
