### ISSUE TITLE
could not trigger k8up newJobs: Backup job already exists

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#306]
## Describe the bug

When reconciling the Schedule object after a Pod restart, K8up cannot reconcile the Schedule to finish, as it encounters an error.

## Additional context

I was trying to upgrade K8up 0.x to 1.x. After restart of K8up, this error below occurred.
Note: I expected the example schedule to have an updated status field with the effective schedule from the check job. But after starting K8up 1.0.0-rc4, this doesn't happen.

## Logs

If applicable, add logs to help explain your problem.
```console
2021-01-20T09:57:00.000+0100	INFO	controllers.Schedule	running schedule for	{"schedule": "default/schedule-global", "job": "backup"}
2021-01-20T09:57:00.000+0100	INFO	controllers.Schedule	running schedule for	{"schedule": "default/schedule-test", "job": "backup"}
2021-01-20T09:57:00.007+0100	INFO	controllers.Backup	adding job to the queue	{"backup": "default/backupjob-1611133020"}
2021-01-20T09:57:00.007+0100	ERROR	controllers.Schedule	could not trigger k8up newJobs	{"schedule": "default/schedule-test", "name": "default/backupjob-1611133020", "error": "backups.backup.appuio.ch \"backupjob-1611133020\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/vshn/k8up/scheduler.(*Scheduler).createObject
	/home/runner/work/k8up/k8up/scheduler/scheduler.go:172
github.com/vshn/k8up/scheduler.(*Scheduler).getScheduleCallback.func1
	/home/runner/work/k8up/k8up/scheduler/scheduler.go:120
github.com/robfig/cron/v3.FuncJob.Run
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
github.com/robfig/cron/v3.(*Cron).startJob.func1
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312
```

## Expected behavior

The schedule should either update the backup job, or delete and recreate

## To Reproduce

2. Commands
```bash
make kind-setup
export KUBECONFIG=${PWD}/testbin/bin/kind-kubeconfig-v1.20.0
kubectl create ns k8up-system
helm -n k8up-system install k8up appuio/k8up
kubectl apply -f config/samples/k8up_v1alpha1_schedule.yaml
kubectl apply -f config/samples/k8up_v1alpha1_prebackuppod.yaml
# wait a few mins to generate jobs
helm uninstall k8up
make crd
kubectl apply -f k8up-crd.yaml
kustomize build config/default | kubectl apply -f -
# now watch the logs
```

## Environment (please complete the following information):

- Image Version: v1.0.0-rc4
- K8s Version: v1.20
- K8s Distribution: KIND

**Comment by ccremer** [comment]
Possible theory, not further investigated:

I think it's a naming problem. Schedules create Backup objects with very generic name like `backupjob-<timestamp>`. If there multiple schedules in the same namespace, with a similar schedule or more precisely: if the happen at the same time, then the names clash with eachother.

Possible solution if verified: use the schedule name as a prefix

**Comment by ccremer** [comment]
I was able to verify this theory. When only 1 schedule exists, then the error vanishes.

**Comment by Kidswiss** [comment]
Is it intended to have multiple schedules in the same namespace? 

If that's a valid use-case I'd suggest to plan for this. In the current state it doesn't make much sense to have more than one schedule anyway. They will both backup the same things. We'd need to introduce some sort of targeting so we can backup different things with different schedules in a single namespace.

**Comment by ccremer** [comment]
> Is it intended to have multiple schedules in the same namespace?

I was not aware of this. And in the documentation I also could not make out that only 1 schedule is permitted to exist per namespace. Additionally, the sample in config/ has specified a test schedule and a global schedule. Maybe fix that as well?

However, I think users can and will create multiple namespaces and we should expect that behaviour, even if it creates the same backups.

**Comment by ccremer** [comment]
It's also possible that users create a schedule for check, prune and archive, but leave the backup spec in another schedule. Either because it may be dynamically generated or updated from CI/CD or script while the others are "static"

We can't really know users are doing. But if only one schedule is permitted, then we should reconcile the other schedule with a condition that says it's being ignored. And documented ofc.

**Comment by Kidswiss** [comment]
If the only issue you've found with running multiple schedules is the naming clash, then it's fine by me if you fix that.

Further improvements to make multiple schedules more useful could be done for later releases.

**Comment by tobru** [comment]
Follow-up for supporting multiple backups: #316
