### ISSUE TITLE
Expose wrestic metrics

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#328]
**As** a k8up user
**I want** I don't want to install prometheus pushgw
**So that** managing k8up installations is easier

## Context

Currently wrestic is sending the metrics to a prometheus push gateway containing a bit more detailed information about the actual job run. Also the operator has a prometheus metrics endpoint that could potentially host the metrics.

While the push gateway is intended to be used in such a fashion it' not really great to use. Also it's another cog in an already complex machine. Getting rid of it makes the whole management easier.

So there should be a way for the operator to collect those metrics and expose them directly.

## Out of Scope

* redefining what the metrics should be

## Acceptance criteria

*Given* an k8up installation
*When* a job finishes
*Then* the metrics will be available in the operator's own metric endpoint

## Implementation Ideas

* termination-log?
* wrestic updates the status of it's job object and the operator updates the metrics accordingly

**Comment by ccremer** [comment]
Given the plan to integrate wrestic into K8up, we should also keep resp. move wrestic's metrics to K8up as well. So closing this issue, please reopen if still somehow relevant.
