### ISSUE TITLE
Update Restic to 0.12.0

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#356]
## Summary

**As** user of K8up
**I want** to make use of the latest [Restic release 0.12.0](https://github.com/restic/restic/releases/tag/v0.12.0)
**So that** prune runs much faster.

## Context

Currently a patched version of Restic is used in wrestic which in itself is suboptimal. Let's switch to upstream again and use the latest release.

## Out of Scope

* Integrating new features of restic 0.12.0, that should be handled in separate issues

## Further links

* https://github.com/restic/restic/releases/tag/v0.12.0
* https://restic.net/blog/2021-02-14/restic-0.12.0-released/
* https://github.com/vshn/wrestic/blob/master/Dockerfile#L11

## Acceptance criteria

*Given* running a prune job
*When* using the Restic 0.12.0
*Then* prune runs through much quicker.

**Comment by Kidswiss** [comment]
Opened a PR here: https://github.com/vshn/wrestic/pull/57

**Comment by Kidswiss** [comment]
Merged in the wrestic repository.
