### ISSUE TITLE
Move wrestic into the K8up repository

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#359]
## Summary

**As** "a k8up developer"\
**I want** "to maintain only one repository"\
**So that** "to reduce the overhead"

## Context

Wrestic is part of k8up and currently lives on its own repository https://github.com/vshn/wrestic. This could be integrated back into this repository so we only have to manage this one.

## Out of Scope

* Any work towards "k8up as a client app"

## Further links

* https://github.com/vshn/wrestic
* https://github.com/vshn/k8up/discussions/232

## Acceptance criteria

*Given* "a k8up developer"\
*When* "when developing k8up"\
*Then* "I only need a single git repo"

## Implementation Ideas

* For a first step I'd simply move everything into here
* In a second step we could go through the code and check for synergies between wrestic and k8up (logging, etc.)

**Comment by ccremer** [comment]
> "k8up as a client app"

How would you differentiate a startup between "operator" and "wrestic" mode resp. how to ensure that the image starts doing a restic backup and not trying to be another Operator?

**Comment by tobru** [comment]
I'm closing that one as this work has been done.
