### ISSUE TITLE
stuck PreBackupPod can cause long backlog of backups which then all start at the same time

### ISSUE THREAD

**Issue by Schnitzel** [vshn/k8up#370]
## Describe the bug

If a namespace has a PreBackupPod defined and that Pod is stuck in creation for any reason (in our situation the PVC could not been mounted), k8up will just wait forever until this pod has started, sometimes days. In the meantime additional backups Objects are created from the Schedule and are all just waiting for the stuck pod.
As soon as the stuck pod is deleted (either manually or during a maintenance) the k8up operator starts all waiting backups at the same time, which in some cases can be hundreds of pods (like if you do backups every 30mins and the backups where stuck for a week).
This causes a huge influx of pods and also many backups at the same time, which I don't think is good for the clusters. See screenshot:

![Lens_-_The_Kubernetes_IDE](https://user-images.githubusercontent.com/750999/108362286-8b063a00-71c1-11eb-8b10-f1dcfcced20a.jpg)

I was able to capture this on video as well:

https://drive.google.com/file/d/173ySK7sJz9IUlTRMRC24BNbY1Y3U9-EQ/view?usp=sharing

## Expected behavior

I'm not exactly sure what I would expect, I could imagine two things:
1. the k8up should realize that an PreBackupPod is stuck and maybe react to that right when the next backup should be started or so. As waiting will just make it worse (more backups piling up). I could imagine that if a new backup is about to be started that the old stuck backup is maybe cancelled (especially if the pod is not created yet, meaning that we know we didn't start a backup yet, so the risk of cancelling a running backup is not there)
2. if we are in a situation where many backups are waiting, it should run them one by one and not at the same time

## To Reproduce

1. create a schedule that runs every 5 mins with PreBackupPod
2. make one PreBackupPod Stuck in creation (not exactly sure how to reproduce, maybe delete the underlining PV for the PVC of the PreBackupPod?)
3. wait 60 mins
4. delete stuck PreBackupPod
5. there should be 11 backups started at the same time

## Environment (please complete the following information):

- Image Version: quay.io/vshn/k8up:v1.0.0-rc6
- K8s Version: v1.18
- K8s Distribution: AWS EKS

**Comment by ccremer** [comment]
Hi
Thank you for the report. @Kidswiss is looking into this in #371 
We are currently discussing expected behaviour 1, where K8up should not retry failed backups (outside what a K8s Job already does with backofflimit).

**Comment by ccremer** [comment]
It took some while, but we're ready with a PR that should fix this issue.
The reason why it took so long is that we had rework the prebackup and job status handling internally.

With the PR, backups go into a Failed state if the deployment failed (progressDeadlineSeconds, defaults to 10min). In that case, the prebackup deployment is also removed, but the same backup object will not be retried. Instead, it is expected that the next backup attempts another try from scratch.
