### ISSUE TITLE
K8up does not clean up check jobs

### ISSUE THREAD

**Issue by gi8lino** [vshn/k8up#393]
## Describe the bug

I set the env variable `BACKUP_GLOBALKEEPJOBS`.
K8up cleans then `prune` and `backup` jobs, but not `check` jobs.

## Expected behavior

If `BACKUP_GLOBALKEEPJOBS` is set, k8up will cleanup `backup`, `check` and `prune` jobs.

## Environment (please complete the following information):

- Image Version: e.g. v1.0.2
- K8s Version: v1.20.4+k3s1
- K8s Distribution: k3s

**Comment by ccremer** [comment]
Hi, thanks for reporting this!

You're right, it looks like it's simply not implemented. @Kidswiss could there be any reasons for that?

**Comment by Kidswiss** [comment]
@ccremer I don't see any reason against it.
