### ISSUE TITLE
e2e-tests fail, blocking release of K8up/wrestic

### ISSUE THREAD

**Issue by ccremer** [vshn/k8up#436]
## Describe the bug

With new wrestic release in #434 the e2e-tests fail repeatedly. 

## Additional context

* They also fail with `make clean e2e-test` locally.
* The impact is not clear. Since we skipped wrestic v0.2.3 in k8up's testing suite, I can't say whether it's the new wrestic or some changes in restic itself.
* We should at least investigate why this happens and figure out if wrestic v0.2.3 and v0.3.0 are safe enough to be used in production.
* It's not clear whether the tests itself are broken or if there's more behind it.

## Logs

If applicable, add logs to help explain your problem.
```console
   ✅  The subject is ready
   secret/k8up-backup-credentials created
   secret/k8up-backup-repo created
   backup.backup.appuio.ch/k8up-k8up-backup created
   Valid expression. Verification in progress...
   Current value for k8up-k8up-backup is <none>...
   Current value for k8up-k8up-backup is <none>...
   k8up-k8up-backup has the right value (true).
   Valid expression. Verification in progress...
   k8up-k8up-backup has the right value (1).
   Waiting for 'backup/k8up-k8up-backup' in namespace 'k8up-e2e-subject' to become 'completed' ...
   backup.backup.appuio.ch/k8up-k8up-backup condition met
   Restic output: 'Error attaching, falling back to logs: unable to upgrade connection: container wrestic-1622039848 not found in pod wrestic-1622039848_k8up-e2e-subject
   [{"time":"2021-05-26T14:37:26.51981169Z","tree":"8f2e9485373c20d0df8a2904defeddb32b5232df7c05e04d1c5e8c90af693924","paths":["/data/subject-pvc"],"hostname":"k8up-e2e-subject","username":"root","id":"3f9e952c02ba4a5ac627558963b28b9770aa45ff72eca5b29694c12fe0a354ac","short_id":"3f9e952c"}]'
   Number of Snapshots >= 1? parse error: Invalid numeric literal at line 1, column 6

```

## Expected behavior

Tests pass

## To Reproduce

2. Commands
```bash
make e2e-test
```

## Environment (please complete the following information):

- Image Version: #434 
- K8s Version: 1.20
- K8s Distribution: kind

**Comment by cimnine** [comment]
I've verified the following so far:

- `make clean e2e-test` on current master (2e90690f47bbdf09cb97c73ce2f0b6929207f6ea) works
- `make clean e2e-test WRESTIC_IMG=quay.io/vshn/wrestic:v0.2.3` on current master (2e90690f47bbdf09cb97c73ce2f0b6929207f6ea) works
- `make clean e2e-test WRESTIC_IMG=quay.io/vshn/wrestic:v0.3.0` on current master (2e90690f47bbdf09cb97c73ce2f0b6929207f6ea) **does not work**
- `make clean e2e-test WRESTIC_IMG=quay.io/vshn/wrestic:latest` on current master (2e90690f47bbdf09cb97c73ce2f0b6929207f6ea) **does not work**

I'm investigating the cause now.
