### ISSUE TITLE
k8up sometimes leaves the restic repository with a stale lock

### ISSUE THREAD

**Issue by smlx** [vshn/k8up#456]
## Describe the bug

Occasionally we see backup failures where the restic repository has a stale lock. See below for logs.

## Additional context

Once a restic repository gets into this state `k8up` cannot recover by itself.
The only way to fix it seems to be to manually run `restic unlock`.

## Logs

```
wrestic/snapshots "level"=0 "msg"="getting list of snapshots"  
wrestic/snapshots/restic "msg"="unable to create lock in backend: repository is already locked exclusively by PID 104 on k8up-foo-backup-schedule-check-d6c6d-tpspc by root (UID 0, GID 0)" "error"="error during command"  
wrestic/snapshots/restic "msg"="lock was created at 2021-07-04 12:04:01 (17h0m36.860846153s ago)" "error"="error during command"  
wrestic/snapshots/restic "msg"="storage ID 23024633" "error"="error during command"  
wrestic/snapshots/restic "msg"="the `unlock` command can be used to remove stale locks" "error"="error during command"  
wrestic "msg"="failed to list snapshots" "error"="EOF"  
```

## Expected behavior

I'd expect that `k8up` can recover from this situation by itself, but I don't know what the best way to recover would be.
Maybe locks older than some configurable period can be removed by `k8up` automatically? For example, by default maybe `k8up` should remove locks older than `12h`?

The only problem I see with that solution is that in some edge cases (e.g. lots of data) a backup may genuinely take `>12h`.
So I guess this should be configurable.

Or maybe there is a better solution altogether?

## To Reproduce

I'm not sure how to reproduce this behaviour, but I suspect that it happens when a backup pod is killed instead of being terminated gracefully.

## Environment:

- Image Version: `quay.io/vshn/k8up:v1.0.5` / `Wrestic Version: v0.2.3-dirty`
- K8s Version: `v1.18.16-eks-7737de`
- K8s Distribution: Amazon EKS

**Comment by Kidswiss** [comment]
Restic itself has an `unlock` feature. It will cleanup all non-exclusive locks that were not renewed within 5 minutes.

Triggering unlock here right before the first repository action in wrestic should do the trick: https://github.com/vshn/wrestic/blob/master/cmd/wrestic/main.go#L85. Unlock itself is already implemented in wrestic: https://github.com/vshn/wrestic/blob/master/restic/unlock.go. But it looks like i'ts not called where necessary.

**Comment by ccremer** [comment]
> I'd expect that k8up can recover from this situation by itself, but I don't know what the best way to recover would be.
Maybe locks older than some configurable period can be removed by k8up automatically? For example, by default maybe k8up should remove locks older than 12h?
The only problem I see with that solution is that in some edge cases (e.g. lots of data) a backup may genuinely take >12h.
So I guess this should be configurable.

@Kidswiss @cimnine Is this something to watch out for?

**Comment by Kidswiss** [comment]
@ccremer 

Restic can handle that on it's own. As long we don't force the cleanup it is save.

>  It will cleanup all non-exclusive locks that were not renewed within 5 minutes.

Context: a running restic job will renew the lock every 5 minutes. So if a lock has not been updated for that time it's considered stale and will be removed by `unlock`.

**Comment by ccremer** [comment]
> Restic can handle that on its own. As long we don't force the cleanup it is save (there's a flag for that. Also already implemented in wrestic.).

From that I can read that it's safe to unlock, correct?

**Comment by Kidswiss** [comment]
Yes. This is a regression. Legacy wrestic actually did an `unlock` very early during a job run.

Something to consider: we should ensure that we only trigger unlock if we're sure there's an initialized repository.
