### ISSUE TITLE
k8up critical errors on non-fatal backup problems

### ISSUE THREAD

**Issue by smlx** [vshn/k8up#459]
## Describe the bug

k8up reports critical errors for non-fatal problems such as files being removed mid-snapshot.

## Additional context

If the mount is in use by another application during the backup, then restic may schedule a file for backup which is removed by the other application before restic is able to read it. This results in a non-fatal error: that is, the snapshot is created by restic exits with a non-zero error code due to files not being able to be read.

Since v0.10.0, restic has distinguished this non-fatal error with exit code 3. See [this restic PR](https://github.com/restic/restic/pull/2546) for details.

## Logs

Here's a snippet of log output showing the problem.

```console
E0714 22:15:25.801829       1 logging.go:156] wrestic/backup/progress "msg"="/data/nginx/styles/large/public/xyz/1111111-22-3333.png during archival lstat" "error"="error occurred during backup"  
I0714 22:16:16.286887       1 logging.go:160] wrestic/backup/progress "level"=0 "msg"="backup finished"  "changed files"=102 "errors"=1 "new files"=857
I0714 22:16:16.286987       1 logging.go:161] wrestic/backup/progress "level"=0 "msg"="stats"  "bytes added"=537839673 "bytes processed"=215990037543 "time"=480.639904657
I0714 22:16:16.287106       1 handler.go:68] wrestic/statsHandler/webhookStats "level"=0 "msg"="sending webhooks"  "url"="https://backup.example.com"
I0714 22:16:16.323187       1 handler.go:44] wrestic/statsHandler/promStats "level"=0 "msg"="sending prometheus stats"  "url"="http://prometheus-pushgateway.insights.svc:9091"
I0714 22:16:16.586841       1 logging.go:150] wrestic/backup/progress "level"=0 "msg"="restic output"  "msg"="Warning: failed to read all source data during backup"
I0714 22:16:16.619126       1 backup.go:43] wrestic/backup "level"=0 "msg"="backup finished, sending snapshot list"
```

## Expected behavior

It would be nice if k8up could somehow distinguish between fatal and non-fatal errors during backup. On a large or busy file storage files are being created or removed regularly so these non-fatal errors pop up with some regularity.

Of course this may actually be a genuine critical error if e.g. file permissions do not allow the file to be read. In that case the error is genuine. I'm not sure how to distinguish between these cases. This may require extra exit codes implemented upstream in restic.

## To Reproduce

1. Have a large PVC that takes some time to backup.
2. Start a backup with `k8up`.
3. Wait for restic to start uploading data. E.g. when it starts logging percentage completion.
4. Delete some files that haven't been uploaded yet.
5. See critical error logged by k8up.

## Environment:

- Image Version: quay.io/vshn/k8up:v1.0.5 / Wrestic Version: v0.2.3-dirty
- K8s Version: v1.18.16-eks-7737de
- K8s Distribution: Amazon EKS

**Comment by Kidswiss** [comment]
Hi @smlx 

Thanks for the report!

Right now wrestic simply ignores the exit code 3 and reports back successful backup. If the exit code is something else, the backup is considered failed and retried.

> It would be nice if k8up could somehow distinguish between fatal and non-fatal errors during backup.
K8up currently does that. Those errors you see in the log aren't considered fatal for k8up. In case of fatal errors it will trigger a retry of the job. If all job retries also fail due to a fatal error the whole backup is considered failed. At that point it should show up in the monitoring.

So I'm not quite sure what your desired behaviour should be? Should those errors only be logged as warnings instead of errors?

Best Regards
Simon

**Comment by smlx** [comment]
Ok thanks for the explanation. I guess the problem must be in our alertmanager configuration.

I don't think there's anything to fix in k8up :slightly_smiling_face:

**Comment by Kidswiss** [comment]
@smlx 

Great that I was able to help you with the explanation!

K8up will report back the file errors separately to a push gateway if it's configured. So maybe that triggers one of your alert rules?

If you find that there's a concrete bug in the alert handling somewhere please open a new issue :)
