### ISSUE TITLE
Merge vshn/wrestic and vshn/k8up Docker images

### ISSUE THREAD

**Issue by cimnine** [vshn/k8up#476]
## Summary

**As** k8up dev\
**I want** just one Docker image for k8up going forward\
**So that** maintenance is simpler.

**As** k8up user\
**I want** just one Docker image for k8up going forward\
**So that** the number of user facing components is reduced to a minimal.

**As** k8up user\
**I want** easy to comprehend modules and components\
**So that** debugging errors of k8up is no lost cause.

## Context

#359 moved the wrestic code into the k8up repository, but did try to changes as little as possible of the architecture.
This ticket shall get rid of the two Docker images.

## Out of Scope

* Update helm chart or commodore component

## Further links

* https://github.com/vshn/k8up/issues/359

## Acceptance criteria

* Given a build of k8up, only one Docker image is created and used throughout.
* Given a release of k8up, the only Docker image is automatically built and published.
* Given there is only one Docker image anymore, all the relevant default configuration is adjusted accordingly.
* Given there is only one Docker image anymore, all the relevant documentation is adjusted accordingly.

## Implementation Ideas

Check where `vshn/wrestic` is used and replace it with `vshn/k8up`. Don't forget to adjust the Docker entrypoint and Docker command ('command' and 'args' in k8s).

**Comment by tobru** [comment]
We could combine this issue with #458 and use the GitHub registry for hosting the image.
