### ISSUE TITLE
Refactor arg and config variables to struct

### ISSUE THREAD

**Issue by cimnine** [vshn/k8up#481]
## Summary

**As** developers\
**I want** control over when variables can be edited\
**So that** I can better reason about what happens in the code and therefore focus on the task at hand.

## Context

#359 moved the wrestic code into the k8up repository, but did try to changes as little as possible of the architecture.

`cmd/restic/main.go` contains the legacy structure with module-scoped variables. These should better be wrapped into it's own struct.

## Out of Scope

* Feature Changes

## Further links

* https://github.com/vshn/k8up/pull/474#discussion_r687471273

## Acceptance criteria

* The number of global or module scoped variables is reduced to the bare minimum.

## Implementation Ideas

The suggestion of @ccremer:

```
type Command struct {
  check bool
  ...
  log logr.Logger
  resticCLI ...
  Command *cli.Command
}
func NewCommand(...) *Command {
  ...
  c.command = &cli.Command{
    Action: c.runCommand,
    ...
  }
}

func (c *Command) runCommand(ctx *cli.Context) error {
...
}
```

Have a look at other code in `cmd/` and elsewhere if they have such avoidable variables as well.

**Comment by tobru** [comment]
This happens in #477, no need for an additional issue.
