### ISSUE TITLE
Upgrade Operator SDK to v1.12

### ISSUE THREAD

**Issue by tobru** [vshn/k8up#503]
Upgrade the Operator SDK to the latest available version. At the time of the creation of this issue it is [v1.12.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.12.0).

See upgrade notes at https://sdk.operatorframework.io/docs/upgrading-sdk-version/

**Comment by ccremer** [comment]
Since we have ditched Operator SDK and are using Kubebuilder natively, this is basically done already in https://github.com/vshn/k8up/pull/441
