### ISSUE TITLE
Is a working PVC backup required for appuio.ch/backupcommand to work?

### ISSUE THREAD

**Issue by dns2utf8** [vshn/k8up#74]
Hi all

I am currently guessing from the code that it should work without a functioning backup.
However, is a prebackup-pod needed? (Suggested by #10)

Best,
Stefan

**Comment by srueg** [comment]
You guessed right, no PVC is required. A prebackup pod is only required if you don't have any other pod to run the backup from. So for example to backup an external DB you could run a prebackup pod which connects to this DB to dump it.

**Comment by dns2utf8** [comment]
That sounds good. For some reason the dump process can not connect to the DB.

```
Listing all pods with annotation appuio.ch/backupcommand in namespace wordpress-demo
Adding wordpress-demo/wordpress-1576140813-554fd58d7f-mb426 to backuplist
backing up via wordpress stdin...
Backup command: mysqldump, -uroot, -pSECRET, --all-databases
command terminated with exit code 2
io: read/write on closed pipe
Stderr of pod exec: 'mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)" when trying to connect
```

**Comment by dns2utf8** [comment]
Does the backup process execute the backup program inside itself or inside the annotated container?

**Comment by srueg** [comment]
Inside the annotated container, via `exec`: https://github.com/vshn/wrestic/blob/master/kubernetes/podExec.go#L27

Sometimes the command might behave weird because it's not executed in a shell. You could try running `/bin/bash -c 'your command'` as a workaround.

**Comment by dns2utf8** [comment]
The solution was this command with all the escapes and different quotes executed with a local bash:
```bash
kubectl -n wordpress-demo annotate pods wordpress-1576140813-mariadb-0 "appuio.ch/backupcommand=/bin/bash -c 'mysqldump -uroot -p\"\${MARIADB_ROOT_PASSWORD}\" --all-databases'" --overwrite
```
It looks like the variables don't get expanded without the shell in-between and one has to be careful so they don't get expanded locally.

**Comment by Kidswiss** [comment]
Would probably make sense to add this to the docs?

@srueg @akosma

**Comment by akosma** [comment]
Absolutely!

**Comment by akosma** [comment]
Documentation addendum via PR: https://github.com/vshn/k8up/pull/83

**Comment by dns2utf8** [comment]
Thank you
