### ISSUE TITLE
Implement support for Restic Tags in Snapshots during Backup & Archive

### ISSUE THREAD

**Issue by Schnitzel** [vshn/k8up#78]
Restic has capabilities to add tags to snapshots: https://restic.readthedocs.io/en/stable/040_backup.html#tags-for-backup
it would be create to define these tags within a `Schedule` object, so we can use these tags to have a bucket a bit organized.

At the same time it would be awesome to define tags in an `Archive` object so that the archive job only takes backups with a given tag into consideration.
In the case of Lagoon I would use the environment type (production, staging or development) for this, so we only archive snapshots of production environments.

**Comment by srueg** [comment]
Implemented by https://github.com/vshn/k8up/pull/94
