### ISSUE TITLE
Future of k8up

### ISSUE THREAD

**Issue by weaktyper** [vshn/k8up#80]
Given the announcement of [Project Syn](https://github.com/projectsyn)

https://vshn.ch/syn/

Is project syn going to take precedence of this repository ?

Should I skip straight to project syn or will support for k8up continue ?

Thanks !

**Comment by tobru** [comment]
Thanks for caring about K8up!

K8up will continue to evolve, no worries. It will probably move under the umbrella of Project Syn, but it will stay the same and get even more traction and development in the future.

**Comment by weaktyper** [comment]
Thanks for clarifying :+1:
