### ISSUE TITLE
`BACKUP_FILEEXTENSIONANNOTATION` and `BACKUP_BACKUPCOMMANDANNOTATION` are not passed to backup pod

### ISSUE THREAD

**Issue by Schnitzel** [vshn/k8up#95]
the `BACKUP_FILEEXTENSIONANNOTATION` and `BACKUP_BACKUPCOMMANDANNOTATION` env variables are used to set the annotations on the PreBackupPods Pods created by wrestic, this  is great. 
The problem is that these env variables are not passed into the backup pod itself, so wrestic is still searching for it's own defaults.

With https://github.com/vshn/k8up/pull/91 the defaults in k8up have changed to be `k8up.syn.tools/*` which is great, but they have not been updated in wrestic, this will be fixed with https://github.com/vshn/wrestic/pull/21. But in my understanding just changing them in k8up should be enough as they should be passed to the backup pod by k8up where they are then picked up by wrestic?

**Comment by Kidswiss** [comment]
Hi @Schnitzel 

I'm tracking this in the internal ticket: https://ticket.vshn.net/browse/APPU-2595

You're correct they should just be passed to the wrestic pods in order to get picked up, but unfortunately the operator doesn't do that yet.

It's planned to be implemented this or next week.

**Comment by srueg** [comment]
Fixed by https://github.com/vshn/k8up/pull/96
